CREATE TABLE TASK (
  ID BIGINT NOT NULL AUTO_INCREMENT,
  SUMMARY VARCHAR(20) NOT NULL,
  PRIORITY VARCHAR(10) NOT NULL DEFAULT 'NORMAL', 
  STATUS VARCHAR(10) NOT NULL DEFAULT 'PENDING',
  DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY(ID)
);                                  

CREATE TABLE TASK_UPDATE (
  ID BIGINT NOT NULL AUTO_INCREMENT,
  TASKID BIGINT NOT NULL,
  TEXT VARCHAR(255) NULL,
  DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY(ID)
);
  
INSERT INTO TASK (SUMMARY) VALUES ('AAA');
INSERT INTO TASK (SUMMARY, PRIORITY, STATUS) VALUES ('BBB', 'LOW', 'REOPENED');